name: "Build Images"

concurrency:
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - main
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *" # every day at midnight, to test against nightlies

jobs:
  create-image:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        kongVersion:
          - "2.8.3"
          - "3.2.2"

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        continue-on-error: false
        run: |
          git config --global url.https://github.com/.insteadOf git@github.com:

          git clone https://github.com/Kong/kong.git
          cd kong
          git checkout tags/$KONG_VERSION
          cd ..

          git clone https://github.com/Kong/kong-build-tools.git
          cd kong-build-tools
          git checkout tags/$KONG_BUILD_TOOLS_VERSION
          cp ../kong-build-tools.patch .
          patch -p1 < ./kong-build-tools.patch

          make build-kong-image-with-modsecurity
        env:
          KONG_VERSION: ${{ matrix.kongVersion }}
          KONG_WITH_MODSECURITY_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.kongVersion }}-ubuntu
          KONG_BUILD_TOOLS_VERSION: "4.42.1"
          BUILDX: 'true'
          DOCKER_PLATFORM: --platform='linux/amd64,linux/arm64'
          DOCKER_PUSH: --push
